services:
  server:
    build: .
    environment:
      VITE_BASE_URL: /${BASE_URL:-pcv}
    ports:
      - 13029
    restart: always
    labels:
      - webproxy.path=${BASE_URL:-pcv}
      - webproxy.websockets=true